modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Nuclearcraft Neoteric"
logoFile = "logo.png"
credits = "tomdodd4598"
authors = "igentuman"
description = '''
A complex nuclear engineering mod for Minecraft
'''

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"